@startuml Cycle Request

skinparam maxMessageSize 300

participant "Data owner" as do
participant PyGrid as grid
database DB as db
database "Parcel\nDocuments" as padb

== Cycle Request ==
do -> grid: request_connect(model_name, model_version, auth_token)
grid -> grid: verify_token(auth_token, model_name)
note left: core/model_centric/auth/federated.py
grid -> grid: assign_worker_id()
note left: events/model_centric/fl_events.py\nCreate and save worker_id
grid -> db: store(worker_id)
note right: worker-cycle table
grid --> do: worker_id

do -> grid: request_cycle(worker_id, model, version, download_times, upload_times)
note left
    def assign in model_centric/controller/fl_controller.py
    check user-provided speedrest result against server config
end note
grid -> grid: cycle_request()
note left
    events/model_centric/fl_events.py\nPerform speed test if necessary,
    check last participation and compare against config
end note
grid --> do: request_key, model_id, training_plan_id
do -> grid: get_model(worker_id, request_key, model_id)
grid --> do: model parameters
do --> grid: get_plan(worker_id, request_key, training_plan_id)
grid --> do: training plan (the serialized function)
do -> do: train()
do -> do: serialize(weight_updates)
do -> padb: store(serialized_weight_updates)
padb --> do: document_id
do -> grid: report(worker_id, request_key, document_id)

@enduml
